/**
 * Live preview server — serves a customizable preview page
 * Tokens update via SSE (Server-Sent Events) for instant browser refresh
 */
import { createServer } from 'node:http';
import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const SAVED_DIR = join(ROOT, 'design-md/original');

function generateDesignMd(t) {
  const isDark = !(t.bg === '#ffffff' || t.bg.includes('f5') || t.bg.includes('fa'));
  return `# DESIGN.md — ${t.brandName}

> AI-readable design system specification.
> Format: [Google Stitch DESIGN.md standard](https://stitch.withgoogle.com/docs/design-md/format/) (9-section)
> Generated by [design-md](https://github.com/applego/design-md) customizer

---

## 1. Visual Theme & Atmosphere

- **Brand**: ${t.brandName}
- **Default mode**: ${isDark ? 'Dark' : 'Light'}

---

## 2. Color Palette & Roles

| Role | Value |
|------|-------|
| Primary | \`${t.primary}\` |
| Primary Light | \`${t.primaryLight}\` |
| Background | \`${t.bg}\` |
| Card | \`${t.card}\` |
| Surface | \`${t.surface}\` |
| Text Primary | \`${t.text}\` |
| Text Secondary | \`${t.textSec}\` |
| Border | \`${t.border}\` |
| Success | \`${t.success}\` |
| Warning | \`${t.warning}\` |
| Danger | \`${t.danger}\` |

---

## 3. Typography Rules

| Role | Stack |
|------|-------|
| Sans | \`${t.fontSans}, "Noto Sans JP", "Hiragino Kaku Gothic ProN", sans-serif\` |
| Mono | \`${t.fontMono}, monospace\` |

### Japanese Typography
- line-height: 1.8 (body)
- letter-spacing: 0.04em
- line-break: strict
- font-feature-settings: "palt"

---

## 4. Component Stylings

| Element | Style |
|---------|-------|
| Button Primary | bg: \`${t.primary}\`, color: #fff, radius: ${t.radius} |
| Button Secondary | bg: \`${t.card}\`, border: 1px solid \`${t.border}\` |
| Card | bg: \`${t.card}\`, border: 1px solid \`${t.border}\`, radius: ${t.radius} |
| Input | bg: \`${t.card}\`, border: 1px solid \`${t.border}\`, radius: ${t.radius} |

---

## 5. Layout Principles

- Spacing base: 4px
- Gaps: 4 / 8 / 12 / 16 / 24px
- Sidebar: 160-192px

---

## 6. Depth & Elevation

| Level | Shadow |
|-------|--------|
| SM | 0 1px 3px rgba(0,0,0,0.06) |
| MD | 0 4px 12px rgba(0,0,0,0.08) |
| LG | 0 8px 24px rgba(0,0,0,0.10) |
| XL | 0 16px 48px rgba(0,0,0,0.14) |

Border Radius: ${t.radius}

---

## 7. Do's and Don'ts

### Do
- Use \`${t.fontMono}\` for financial/numerical values
- Apply semantic colors: \`${t.success}\` (success), \`${t.warning}\` (warning), \`${t.danger}\` (danger)

### Don't
- Don't hardcode pixel values outside the spacing scale
- Don't add colors outside this palette

---

## 8. Responsive Behavior

| Breakpoint | Width |
|------------|-------|
| sm | >= 640px |
| md | >= 768px |
| lg | >= 1024px |

---

## 9. Agent Prompt Guide

\`\`\`
Primary:    ${t.primary}
Background: ${t.bg}
Text:       ${t.text}
Success:    ${t.success}
Warning:    ${t.warning}
Danger:     ${t.danger}
Font Sans:  ${t.fontSans}
Font Mono:  ${t.fontMono}
Radius:     ${t.radius}
\`\`\`
`;
}

const PREVIEW_HTML = (tokens) => `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DESIGN.md Live Preview</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+JP:wght@400;500;700&family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">
<style>
  :root {
    --primary: ${tokens.primary};
    --primary-light: ${tokens.primaryLight};
    --bg: ${tokens.bg};
    --card: ${tokens.card};
    --surface: ${tokens.surface};
    --text: ${tokens.text};
    --text-sec: ${tokens.textSec};
    --border: ${tokens.border};
    --success: ${tokens.success};
    --warning: ${tokens.warning};
    --danger: ${tokens.danger};
    --radius: ${tokens.radius};
    --font: '${tokens.fontSans}', 'Noto Sans JP', sans-serif;
    --mono: '${tokens.fontMono}', monospace;
  }
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:var(--font);background:var(--bg);color:var(--text);padding:24px;transition:all .3s}
  .header{margin-bottom:24px}
  .header h1{font-size:20px;font-weight:700;margin-bottom:4px}
  .header p{font-size:12px;color:var(--text-sec)}
  .live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#22c55e;margin-right:6px;animation:pulse 2s infinite}
  @keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}

  .section{margin-bottom:28px}
  .section-title{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.15em;color:var(--text-sec);margin-bottom:10px}

  .color-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(100px,1fr));gap:6px}
  .color-chip{border-radius:var(--radius);padding:10px;min-height:64px;display:flex;flex-direction:column;justify-content:flex-end}
  .color-chip .label{font-size:9px;font-weight:600}
  .color-chip .hex{font-size:10px;font-family:var(--mono)}

  .badges-row{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:8px}
  .badge{padding:2px 8px;border-radius:calc(var(--radius) / 2);font-size:9px;font-weight:700;text-transform:uppercase}

  .components-row{display:flex;gap:12px;flex-wrap:wrap}
  .card-demo{border-radius:var(--radius);padding:14px;width:260px;background:var(--card);border:1px solid var(--border)}
  .card-demo h3{font-size:13px;font-weight:700;margin-bottom:4px}
  .card-demo p{font-size:11px;color:var(--text-sec);margin-bottom:10px}
  .metrics-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px}
  .metric-box{border-radius:calc(var(--radius) / 2);padding:7px;background:var(--surface)}
  .metric-box .m-label{font-size:8px;color:var(--text-sec)}
  .metric-box .m-value{font-size:13px;font-weight:700;font-family:var(--mono)}

  .sidebar-demo{width:160px;border-radius:var(--radius);padding:6px;background:var(--surface);border:1px solid var(--border)}
  .nav-item{display:flex;align-items:center;gap:7px;padding:5px 8px;border-radius:calc(var(--radius) / 2);font-size:11px;font-weight:500;color:var(--text-sec)}
  .nav-item.active{background:var(--primary-light);color:var(--primary);font-weight:600}
  .nav-icon{width:12px;height:12px;border-radius:3px;background:currentColor;opacity:.4;flex-shrink:0}
  .nav-item.active .nav-icon{opacity:.8}

  .btn-group{display:flex;gap:6px;flex-wrap:wrap}
  .btn{padding:6px 14px;border-radius:var(--radius);font-size:11px;font-weight:600;border:none;cursor:pointer;font-family:var(--font)}
  .btn-primary{background:var(--primary);color:#fff}
  .btn-secondary{background:var(--card);border:1px solid var(--border);color:var(--text-sec)}
  .btn-ghost{background:transparent;color:var(--text-sec)}

  .tab-bar{display:inline-flex;gap:2px;border-radius:var(--radius);padding:3px;background:var(--surface);border:1px solid var(--border)}
  .tab-item{padding:5px 12px;border-radius:calc(var(--radius) / 2);font-size:11px;font-weight:600;background:transparent;color:var(--text-sec);border:none;font-family:var(--font)}
  .tab-item.active{background:var(--card);color:var(--text);box-shadow:0 1px 3px rgba(0,0,0,.08)}

  .input-demo{border-radius:var(--radius);padding:8px 12px;font-size:12px;border:1px solid var(--border);width:220px;font-family:var(--font);background:var(--card);color:var(--text)}

  .shadow-demo{display:flex;gap:14px}
  .shadow-box{width:72px;height:72px;border-radius:var(--radius);display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:600;background:var(--card);color:var(--text-sec)}

  .jp-typo{padding:14px;border-radius:var(--radius);background:var(--card);border:1px solid var(--border)}

  .token-bar{position:fixed;bottom:0;left:0;right:0;background:var(--surface);border-top:1px solid var(--border);padding:8px 16px;font-size:10px;color:var(--text-sec);font-family:var(--mono);display:flex;gap:16px;flex-wrap:wrap;backdrop-filter:blur(12px)}
  .token-bar span{white-space:nowrap}
</style>
</head>
<body>
<div class="header">
  <h1><span class="live-dot"></span>${tokens.brandName || 'Custom'} — Live Preview</h1>
  <p>Wizard で変更すると自動更新されます</p>
</div>

<div class="section">
  <div class="section-title">Colors</div>
  <div class="color-grid">
    <div class="color-chip" style="background:${tokens.primary};color:#fff"><div class="label">Primary</div><div class="hex">${tokens.primary}</div></div>
    <div class="color-chip" style="background:${tokens.primaryLight};color:${tokens.primary}"><div class="label">Primary Lt</div><div class="hex">${tokens.primaryLight}</div></div>
    <div class="color-chip" style="background:${tokens.bg};color:${tokens.text};border:1px solid ${tokens.border}"><div class="label">Background</div><div class="hex">${tokens.bg}</div></div>
    <div class="color-chip" style="background:${tokens.card};color:${tokens.text};border:1px solid ${tokens.border}"><div class="label">Card</div><div class="hex">${tokens.card}</div></div>
    <div class="color-chip" style="background:${tokens.surface};color:${tokens.text}"><div class="label">Surface</div><div class="hex">${tokens.surface}</div></div>
    <div class="color-chip" style="background:${tokens.success};color:#fff"><div class="label">Success</div><div class="hex">${tokens.success}</div></div>
    <div class="color-chip" style="background:${tokens.warning};color:#fff"><div class="label">Warning</div><div class="hex">${tokens.warning}</div></div>
    <div class="color-chip" style="background:${tokens.danger};color:#fff"><div class="label">Danger</div><div class="hex">${tokens.danger}</div></div>
  </div>
</div>

<div class="section">
  <div class="section-title">Badges</div>
  <div class="badges-row">
    <span class="badge" style="background:${tokens.success}22;color:${tokens.success}">承認済</span>
    <span class="badge" style="background:${tokens.warning}22;color:${tokens.warning}">確認中</span>
    <span class="badge" style="background:${tokens.danger}22;color:${tokens.danger}">却下</span>
    <span class="badge" style="background:${tokens.primary}22;color:${tokens.primary}">売上</span>
    <span class="badge" style="background:#7c3aed22;color:#7c3aed">AI提案</span>
  </div>
</div>

<div class="section">
  <div class="section-title">Typography</div>
  <div style="font-size:20px;font-weight:700;margin-bottom:6px">月次損益レポート</div>
  <div style="font-size:14px;font-weight:700;margin-bottom:4px">売上高推移 — 2026年Q1</div>
  <div style="font-size:12px;color:var(--text-sec);margin-bottom:4px">freeeから取得した取引データを元に、AIが仕訳候補を自動生成しました。</div>
  <div style="font-size:14px;font-weight:700;font-family:var(--mono)">¥12,450,000 <span style="font-size:11px;opacity:.5">(+8.3%)</span></div>
</div>

<div class="section">
  <div class="section-title">Japanese Typography</div>
  <div class="jp-typo">
    <p style="font-size:14px;line-height:1.8;letter-spacing:.04em;margin-bottom:6px">損益計算書（PL）は、企業の一定期間における経営成績を示す財務諸表です。売上高から各種費用を差し引き、最終的な利益を算出します。</p>
    <p style="font-size:11px;color:var(--text-sec)">font: ${tokens.fontSans} + Noto Sans JP / line-height: 1.8</p>
  </div>
</div>

<div class="section">
  <div class="section-title">Buttons</div>
  <div class="btn-group">
    <button class="btn btn-primary">承認する</button>
    <button class="btn btn-secondary">差し戻し</button>
    <button class="btn btn-ghost">キャンセル</button>
  </div>
</div>

<div class="section">
  <div class="section-title">Tab Bar</div>
  <div class="tab-bar">
    <button class="tab-item active">レビュー</button>
    <button class="tab-item">仕訳一覧</button>
    <button class="tab-item">PL推移</button>
    <button class="tab-item">設定</button>
  </div>
</div>

<div class="section">
  <div class="section-title">Cards & Sidebar</div>
  <div class="components-row">
    <div class="card-demo">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:4px">
        <h3>仕訳レビュー #1042</h3>
        <span class="badge" style="background:${tokens.success}22;color:${tokens.success};font-size:8px">HIGH 92%</span>
      </div>
      <p>Amazon Web Services — サーバー利用料</p>
      <div class="metrics-grid">
        <div class="metric-box"><div class="m-label">借方</div><div class="m-value">通信費</div></div>
        <div class="metric-box"><div class="m-label">金額</div><div class="m-value" style="color:${tokens.warning}">¥245,800</div></div>
        <div class="metric-box"><div class="m-label">ソース</div><div class="m-value" style="font-size:10px">freee</div></div>
        <div class="metric-box"><div class="m-label">前月比</div><div class="m-value" style="color:${tokens.danger}">+12.3%</div></div>
      </div>
    </div>
    <div class="sidebar-demo">
      <div style="font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.12em;color:var(--text-sec);opacity:.5;padding:6px 8px">MAIN</div>
      <div class="nav-item active"><div class="nav-icon"></div>ホーム</div>
      <div class="nav-item"><div class="nav-icon"></div>レビュー</div>
      <div class="nav-item"><div class="nav-icon"></div>プロジェクト</div>
      <div class="nav-item"><div class="nav-icon"></div>メンバー</div>
      <div class="nav-item"><div class="nav-icon"></div>チャット</div>
    </div>
  </div>
</div>

<div class="section">
  <div class="section-title">Input</div>
  <input class="input-demo" placeholder="勘定科目を検索..." />
</div>

<div class="section">
  <div class="section-title">Elevation</div>
  <div class="shadow-demo">
    <div class="shadow-box" style="box-shadow:0 1px 3px rgba(0,0,0,.06)">SM</div>
    <div class="shadow-box" style="box-shadow:0 4px 12px rgba(0,0,0,.08)">MD</div>
    <div class="shadow-box" style="box-shadow:0 8px 24px rgba(0,0,0,.1)">LG</div>
    <div class="shadow-box" style="box-shadow:0 16px 48px rgba(0,0,0,.14)">XL</div>
  </div>
</div>

<!-- Customizer panel -->
<button id="toggle-customizer" style="position:fixed;top:16px;right:16px;z-index:1000;background:${tokens.primary};color:#fff;border:none;border-radius:8px;padding:8px 14px;font-size:12px;font-weight:600;cursor:pointer;font-family:var(--font)">🎨 Customize</button>

<div id="customizer" style="position:fixed;top:0;right:-420px;width:400px;height:100vh;background:${tokens.card};border-left:1px solid ${tokens.border};z-index:999;padding:24px;overflow-y:auto;transition:right .3s;box-shadow:-4px 0 24px rgba(0,0,0,.08);font-family:var(--font)">
  <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px">
    <h2 style="font-size:16px;font-weight:700;color:${tokens.text}">Customize</h2>
    <button id="close-customizer" style="background:transparent;border:none;font-size:20px;cursor:pointer;color:${tokens.textSec}">✕</button>
  </div>

  <div style="margin-bottom:12px">
    <label style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:${tokens.textSec};display:block;margin-bottom:6px">Brand Name</label>
    <input type="text" id="t-brandName" value="${tokens.brandName}" style="width:100%;padding:8px 10px;border:1px solid ${tokens.border};border-radius:6px;font-size:13px;background:${tokens.bg};color:${tokens.text};font-family:inherit">
  </div>

  <details open style="margin-bottom:12px">
    <summary style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:${tokens.textSec};cursor:pointer;padding:6px 0">Colors</summary>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px" id="color-pickers"></div>
  </details>

  <details open style="margin-bottom:12px">
    <summary style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:${tokens.textSec};cursor:pointer;padding:6px 0">Fonts</summary>
    <div style="margin-top:8px">
      <label style="font-size:11px;color:${tokens.textSec};display:block;margin-bottom:4px">Sans (body)</label>
      <select id="t-fontSans" style="width:100%;padding:7px;border:1px solid ${tokens.border};border-radius:6px;font-size:13px;background:${tokens.bg};color:${tokens.text};margin-bottom:8px"></select>
      <label style="font-size:11px;color:${tokens.textSec};display:block;margin-bottom:4px">Mono (metrics)</label>
      <select id="t-fontMono" style="width:100%;padding:7px;border:1px solid ${tokens.border};border-radius:6px;font-size:13px;background:${tokens.bg};color:${tokens.text}"></select>
    </div>
  </details>

  <details style="margin-bottom:12px">
    <summary style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:${tokens.textSec};cursor:pointer;padding:6px 0">Radius</summary>
    <div style="margin-top:8px">
      <input type="text" id="t-radius" value="${tokens.radius}" placeholder="8px" style="width:100%;padding:8px;border:1px solid ${tokens.border};border-radius:6px;font-size:13px;background:${tokens.bg};color:${tokens.text};font-family:inherit">
      <div style="display:flex;gap:4px;margin-top:4px">
        ${['0px','4px','6px','8px','10px','12px','16px','50%'].map(r => `<button class="radius-preset" data-r="${r}" style="padding:4px 8px;font-size:10px;border:1px solid ${tokens.border};background:${tokens.bg};color:${tokens.text};border-radius:4px;cursor:pointer;font-family:inherit">${r}</button>`).join('')}
      </div>
    </div>
  </details>

  <div style="display:flex;gap:8px;margin-top:20px;padding-top:16px;border-top:1px solid ${tokens.border}">
    <button id="save-design-md" style="flex:1;background:${tokens.primary};color:#fff;border:none;border-radius:8px;padding:10px;font-size:13px;font-weight:700;cursor:pointer;font-family:inherit">💾 Save DESIGN.md</button>
    <button id="reset-tokens" style="background:transparent;color:${tokens.textSec};border:1px solid ${tokens.border};border-radius:8px;padding:10px 14px;font-size:12px;cursor:pointer;font-family:inherit">Reset</button>
  </div>

  <div id="save-result" style="margin-top:12px;font-size:11px;color:${tokens.textSec};font-family:var(--mono)"></div>
</div>

<div class="token-bar">
  <span>primary: ${tokens.primary}</span>
  <span>bg: ${tokens.bg}</span>
  <span>font: ${tokens.fontSans}</span>
  <span>radius: ${tokens.radius}</span>
  <span>mode: ${tokens.bg === '#ffffff' || tokens.bg.includes('f5') ? 'light' : 'dark'}</span>
</div>

<script>
  const es = new EventSource('/sse');
  es.onmessage = () => location.reload();

  const tokens = ${JSON.stringify(tokens)};
  const COLOR_KEYS = ['primary','primaryLight','bg','card','surface','text','textSec','border','success','warning','danger'];
  const FONT_OPTIONS_SANS = ['Inter','Noto Sans JP','Hiragino Sans','Yu Gothic','Geist','SF Pro','Helvetica Neue','Roboto','Circular','Söhne','Cal Sans','Figma Sans'];
  const FONT_OPTIONS_MONO = ['JetBrains Mono','Geist Mono','SF Mono','Berkeley Mono','IBM Plex Mono','Source Code Pro','monospace'];

  // Build color pickers
  const cpContainer = document.getElementById('color-pickers');
  cpContainer.innerHTML = COLOR_KEYS.map(k => {
    const v = tokens[k] || '#000000';
    const isHex = /^#[0-9a-f]{6}/i.test(v);
    const colorVal = isHex ? v.slice(0,7) : '#000000';
    return \`<div>
      <label style="font-size:10px;color:${tokens.textSec};display:block;margin-bottom:2px">\${k}</label>
      <div style="display:flex;gap:4px;align-items:center">
        <input type="color" data-key="\${k}" value="\${colorVal}" style="width:30px;height:30px;padding:0;border:1px solid ${tokens.border};border-radius:4px;cursor:pointer">
        <input type="text" data-key="\${k}" value="\${v}" style="flex:1;padding:5px 6px;border:1px solid ${tokens.border};border-radius:4px;font-size:10px;font-family:var(--mono);background:${tokens.bg};color:${tokens.text}">
      </div>
    </div>\`;
  }).join('');

  // Build font selectors
  const sansSel = document.getElementById('t-fontSans');
  const monoSel = document.getElementById('t-fontMono');
  sansSel.innerHTML = FONT_OPTIONS_SANS.map(f => \`<option value="\${f}" \${f===tokens.fontSans?'selected':''}>\${f}</option>\`).join('');
  monoSel.innerHTML = FONT_OPTIONS_MONO.map(f => \`<option value="\${f}" \${f===tokens.fontMono?'selected':''}>\${f}</option>\`).join('');

  // Send update to server
  async function updateToken(key, value) {
    await fetch('/tokens', {
      method: 'POST',
      headers: {'Content-Type':'application/json'},
      body: JSON.stringify({[key]: value})
    });
  }

  // Color picker sync (color ↔ text input)
  cpContainer.addEventListener('input', e => {
    const key = e.target.dataset.key;
    if (!key) return;
    const val = e.target.value;
    // Sync the other input for same key
    cpContainer.querySelectorAll(\`[data-key="\${key}"]\`).forEach(el => {
      if (el !== e.target && /^#[0-9a-f]{6}/i.test(val)) el.value = val.slice(0,7);
    });
    if (/^#[0-9a-f]{3,8}|rgba?|hsla?/i.test(val) || val.length > 3) {
      updateToken(key, val);
    }
  });

  // Brand name
  document.getElementById('t-brandName').addEventListener('input', e => updateToken('brandName', e.target.value));

  // Fonts
  sansSel.addEventListener('change', e => updateToken('fontSans', e.target.value));
  monoSel.addEventListener('change', e => updateToken('fontMono', e.target.value));

  // Radius
  const radiusInput = document.getElementById('t-radius');
  radiusInput.addEventListener('input', e => updateToken('radius', e.target.value));
  document.querySelectorAll('.radius-preset').forEach(btn => {
    btn.addEventListener('click', () => {
      const r = btn.dataset.r;
      radiusInput.value = r;
      updateToken('radius', r);
    });
  });

  // Toggle customizer
  const panel = document.getElementById('customizer');
  const toggleBtn = document.getElementById('toggle-customizer');
  toggleBtn.addEventListener('click', () => { panel.style.right = '0'; toggleBtn.style.display = 'none'; });
  document.getElementById('close-customizer').addEventListener('click', () => { panel.style.right = '-420px'; toggleBtn.style.display = 'block'; });

  // Save DESIGN.md
  document.getElementById('save-design-md').addEventListener('click', async () => {
    const name = document.getElementById('t-brandName').value || 'custom';
    const safeName = name.toLowerCase().replace(/[^a-z0-9-]/g,'-');
    const resEl = document.getElementById('save-result');
    resEl.textContent = 'Saving...';
    try {
      const res = await fetch('/save', {
        method: 'POST',
        headers: {'Content-Type':'application/json'},
        body: JSON.stringify({ name: safeName })
      });
      const data = await res.json();
      if (data.ok) {
        resEl.innerHTML = \`✅ Saved: <a href="/saved/\${safeName}/DESIGN.md" target="_blank" style="color:${tokens.primary}">\${data.path}</a>\`;
      } else {
        resEl.textContent = '❌ ' + (data.error || 'save failed');
      }
    } catch(e) {
      resEl.textContent = '❌ ' + e.message;
    }
  });

  // Reset
  document.getElementById('reset-tokens').addEventListener('click', async () => {
    if (!confirm('デフォルトにリセット？')) return;
    await fetch('/reset', { method: 'POST' });
  });
</script>
</body>
</html>`;

export function createPreviewServer(initialTokens) {
  const defaultTokens = { ...initialTokens };
  let tokens = { ...initialTokens };
  let sseClients = [];

  const notifyReload = () => {
    for (const client of sseClients) client.write('data: reload\n\n');
  };

  const server = createServer(async (req, res) => {
    // CORS preflight (OPTIONS)
    if (req.method === 'OPTIONS') {
      res.writeHead(204, {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Max-Age': '86400',
      });
      res.end();
      return;
    }

    if (req.url === '/sse') {
      res.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
        'Access-Control-Allow-Origin': '*',
      });
      sseClients.push(res);
      req.on('close', () => { sseClients = sseClients.filter(c => c !== res); });
      return;
    }

    // POST /tokens — update tokens via HTTP API (for Claude Code integration)
    if (req.method === 'POST' && req.url === '/tokens') {
      let body = '';
      req.on('data', c => body += c);
      req.on('end', () => {
        try {
          const newTokens = JSON.parse(body);
          tokens = { ...tokens, ...newTokens };
          for (const client of sseClients) {
            client.write('data: reload\n\n');
          }
          res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ ok: true, tokens }));
        } catch (e) {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ error: e.message }));
        }
      });
      return;
    }

    // GET /tokens — read current tokens
    if (req.url === '/tokens') {
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(JSON.stringify(tokens));
      return;
    }

    // POST /save — save current tokens as a new DESIGN.md
    if (req.method === 'POST' && req.url === '/save') {
      let body = '';
      req.on('data', c => body += c);
      req.on('end', async () => {
        try {
          const { name } = JSON.parse(body);
          const safeName = String(name || 'custom').toLowerCase().replace(/[^a-z0-9-]/g, '-').slice(0, 50) || 'custom';
          const dir = join(SAVED_DIR, safeName);
          await mkdir(dir, { recursive: true });
          const md = generateDesignMd(tokens);
          await writeFile(join(dir, 'DESIGN.md'), md);
          // Also write meta.json for gallery integration
          const meta = {
            name: safeName,
            source: 'original',
            category: ['custom'],
            mood: ['custom'],
            primaryColor: tokens.primary,
            fonts: { sans: tokens.fontSans, mono: tokens.fontMono },
            hasJpTypo: true,
            hasDarkMode: !(tokens.bg === '#ffffff' || tokens.bg.includes('f5')),
            sections: 9,
            lastSynced: new Date().toISOString().split('T')[0],
            tokens: { ...tokens },
          };
          await writeFile(join(dir, 'meta.json'), JSON.stringify(meta, null, 2));
          res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ ok: true, path: `design-md/original/${safeName}/DESIGN.md`, dir }));
        } catch (e) {
          res.writeHead(500, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ error: e.message }));
        }
      });
      return;
    }

    // GET /saved/:name/DESIGN.md — view saved design
    if (req.url.startsWith('/saved/')) {
      const match = req.url.match(/^\/saved\/([a-z0-9-]+)\/DESIGN\.md$/);
      if (match) {
        const path = join(SAVED_DIR, match[1], 'DESIGN.md');
        if (existsSync(path)) {
          const content = await readFile(path, 'utf-8');
          res.writeHead(200, { 'Content-Type': 'text/markdown; charset=utf-8' });
          res.end(content);
          return;
        }
      }
    }

    // POST /reset — reset to default tokens
    if (req.method === 'POST' && req.url === '/reset') {
      tokens = { ...defaultTokens };
      notifyReload();
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(JSON.stringify({ ok: true, tokens }));
      return;
    }

    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(PREVIEW_HTML(tokens));
  });

  return {
    start(port = 0) {
      return new Promise(resolve => {
        server.listen(port, () => {
          const addr = server.address();
          resolve(addr.port);
        });
      });
    },
    update(newTokens) {
      tokens = { ...tokens, ...newTokens };
      for (const client of sseClients) {
        client.write('data: reload\n\n');
      }
    },
    getTokens() { return { ...tokens }; },
    stop() { server.close(); },
  };
}
